# Generated by Django 6.1.1 on 2026-09-28 15:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_friendrequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HardwareProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpu', models.CharField(max_length=200)),
                ('gpu', models.CharField(max_length=200)),
                ('ram_gb', models.IntegerField()),
                ('vram_gb', models.IntegerField(blank=True, null=True)),
                ('operating_system', models.CharField(blank=True, max_length=200)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hardware_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
