# Generated by Django 6.1.1 on 2026-09-28 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_hardwareprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minimum_cpu', models.CharField(max_length=200)),
                ('minimum_gpu', models.CharField(max_length=200)),
                ('minimum_ram_gb', models.IntegerField()),
                ('recommended_cpu', models.CharField(max_length=200)),
                ('recommended_gpu', models.CharField(max_length=200)),
                ('recommended_ram_gb', models.IntegerField()),
                ('game', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='core.game')),
            ],
        ),
    ]
