# Generated by Django 6.1.1 on 2026-09-28 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_gamerequirement'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamerequirement',
            name='minimum_network',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='gamerequirement',
            name='minimum_storage',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='gamerequirement',
            name='recommended_network',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='gamerequirement',
            name='recommended_storage',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='gamerequirement',
            name='minimum_cpu',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='gamerequirement',
            name='minimum_gpu',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='gamerequirement',
            name='recommended_cpu',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='gamerequirement',
            name='recommended_gpu',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
