# Generated by Django 6.1.1 on 2026-10-02 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_game_price_videotutorial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HardwareProfile',
        ),
    ]
