# Generated by Django 6.1.1 on 2026-10-05 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_review_status'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='libraryentry',
            name='unique_library_game',
        ),
        migrations.RemoveConstraint(
            model_name='purchase',
            name='unique_user_purchase',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='game',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='user',
        ),
        migrations.DeleteModel(
            name='LibraryEntry',
        ),
        migrations.DeleteModel(
            name='Purchase',
        ),
    ]
